version: '3.8'
services:

  #PHP Service
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes: 
      - ./laravel:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./laravel:/var/www
      - ./.docker/server/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./.docker/databases/my.cnf:/etc/mysql/my.cnf
      - ./.docker/databases/data:/var/lib/mysql
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge